apiVersion: apps/v1
kind: Deployment
metadata:
  name: astonvilla-fe-deployment
  labels:
    app: astonvilla-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: astonvilla-fe
  template:
    metadata:
      labels:
        app: astonvilla-fe
    spec:
      containers:
      - name: astonvilla-fe
        image: akrout97/astonvilla-fe
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: astonvilla-fe
spec:
  type: NodePort
  selector:
    app: astonvilla-fe
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
      nodePort: 30002